"""init

Revision ID: 0af6e1b5fe0a
Revises: 
Create Date: 2019-08-21 00:29:09.135933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af6e1b5fe0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_sessions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
